name: New Release - Update other projects
'on':
  repository_dispatch:
    types:
    - http4k-release
jobs:
  create-upgrade-branches:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
        - http4k/demo
        - http4k/examples
        - http4k/http4k-bin
        - http4k/http4k-by-example
        - http4k/http4k-oidc
        - http4k/mcp-desktop
        - http4k/intellij-plugin
        - http4k/lts-examples
        - http4k/toolbox
        - http4k/www
    steps:
    - name: Trigger ${{ matrix.repo }}
      run: |-
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GH_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ matrix.repo }}/dispatches \
          -d '{"event_type":"http4k-release","client_payload":{"version":"${{ github.event.client_payload.version }}"}}'
      env:
        GH_TOKEN: ${{ secrets.TOOLBOX_REPO_TOKEN }}
      shell: bash