name: New Release - GitHub
'on':
  repository_dispatch:
    types:
    - http4k-release
permissions:
  contents: read
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    - name: Build release note
      run: bin/build_release_note.sh ${{ github.event.client_payload.version }} > NOTE.md
      shell: bash
    - name: Create Release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        tag_name: ${{ github.event.client_payload.version }}
        release_name: ${{ github.event.client_payload.version }}
        body_path: NOTE.md
        draft: false
        prerelease: false
    permissions:
      contents: write
