name: Update Dependencies
'on':
  workflow_dispatch: {
    }
  schedule:
  - cron: 0 7 * * 1
jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    name: Update Version Catalog
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
      with:
        ref: master
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Java
      uses: actions/setup-java@v5.0.0
      with:
        java-version: '21'
        distribution: adopt
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4.4.2
    - name: Create dependency update branch
      run: |-
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git checkout -b dependency-update
      shell: bash
    - name: Update version catalog
      run: ./gradlew versionCatalogUpdate --no-daemon
      shell: bash
    - name: Check for changes
      id: verify-changed-files
      run: |-
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "Changes detected in version catalog"
        else
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "No changes detected"
        fi
      shell: bash
    - name: Build
      if: steps.verify-changed-files.outputs.changed == 'true'
      timeout-minutes: 120
      run: bin/build_ci.sh
      env:
        HONEYCOMB_API_KEY: ${{ secrets.HONEYCOMB_API_KEY }}
        HONEYCOMB_DATASET: ${{ secrets.HONEYCOMB_DATASET }}
      shell: bash
    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |-
        git add gradle/libs.versions.toml
        git commit -m "Update dependency versions

        > Automated dependency update using version-catalog-update-plugin

        This PR was automatically created by GitHub Actions to update dependencies to their latest versions."
        git push --force --set-upstream origin dependency-update
      shell: bash
    - name: Create Pull Request
      if: steps.verify-changed-files.outputs.changed == 'true'
      uses: repo-sync/pull-request@v2
      with:
        source_branch: dependency-update
        destination_branch: master
        pr_title: = Update dependencies to latest versions
        pr_body: |-
          ## > Automated Dependency Update

          This PR was automatically created to update dependencies to their latest versions using the [version-catalog-update-plugin](https://github.com/littlerobots/version-catalog-update-plugin).

          ### Changes
          - Updated `gradle/libs.versions.toml` with latest stable dependency versions

          ### What to do next
          1. Review the changes in `gradle/libs.versions.toml`
          2. Run tests locally or wait for CI to complete
          3. Merge if all tests pass

          **Note:** Only stable versions are included in this update.
        pr_draft: 'false'
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: No changes
      if: steps.verify-changed-files.outputs.changed == 'false'
      run: echo "No dependency updates available"
      shell: bash