name: Release API
'on':
  workflow_dispatch:
jobs:
  release-api:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    - name: Setup Java
      uses: actions/setup-java@v5.0.0
      with:
        java-version: '21'
        distribution: adopt
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4.4.2
    - name: Generate API docs
      run: ./gradlew -i dokkaGenerateHtml -PreleaseVersion="6.18.0.1" -Porg.gradle.parallel=false
      shell: bash
    - name: Checkout API repo
      uses: actions/checkout@v5.0.0
      with:
        repository: http4k/api
        token: ${{ secrets.AUTHOR_TOKEN }}
        path: tmp
    - name: Copy docs
      run: cp -R build/docs/api/html/* tmp/
      shell: bash
    - name: Commit API docs
      uses: EndBug/add-and-commit@v9
      with:
        cwd: tmp
        message: release API docs
      env:
        GITHUB_TOKEN: ${{ secrets.AUTHOR_TOKEN }}
    - name: Push API docs
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.AUTHOR_TOKEN }}
        directory: tmp
        repository: http4k/api
