name: tmp.yml
on:
  workflow_dispatch:

jobs:
  dump-event:
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJson(github.event) }}" > event.json
        shell: bash

  check-new-version:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    outputs:
        version: ${{ steps.set-version.outputs.version }}
    steps:
      - id: set-version
        run: echo "version=6.18.0.1" >> $GITHUB_OUTPUT

  broadcast-release:
    if: github.event_name == 'workflow_dispatch'
    needs: check-new-version
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    - name: Grab tag name
      id: tagName
      uses: olegtarasov/get-tag@v2.1.4
    - name: Repository Dispatch
      run: |-
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GH_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type":"http4k-release","client_payload":{"version":"${{ needs.check-new-version.outputs.version }}"}}'
      env:
        GH_TOKEN: ${{ secrets.ORG_PUBLIC_REPO_WORKFLOW_TRIGGERING }}
      shell: bash
